#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  Aug 07, 2019 09:42:19 AM CEST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 11 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 436x433+750+183
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1684 1031
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 185 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 255 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Node default} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Actual node} 
    vTcl:DefineAlias "$site_3_0.lab68" "Label1_10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab69 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Default edge} 
    vTcl:DefineAlias "$site_3_0.lab69" "Label1_11" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab70 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Edge player 1} 
    vTcl:DefineAlias "$site_3_0.lab70" "Label1_12" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab71 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Edge player 2} 
    vTcl:DefineAlias "$site_3_0.lab71" "Label1_13" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab78 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Border edge} 
    vTcl:DefineAlias "$site_3_0.lab78" "Label1_14" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab80 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -relief groove 
    vTcl:DefineAlias "$site_3_0.lab80" "lblColorNodeDefault" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.lab80 <Button-1> {
        lambda e: lblColorPicker_OnClick(e)
    }
    label $site_3_0.lab81 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -relief groove 
    vTcl:DefineAlias "$site_3_0.lab81" "lblColorNodeActual" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.lab81 <Button-1> {
        lambda e: lblColorPicker_OnClick(e)
    }
    label $site_3_0.lab82 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -relief groove 
    vTcl:DefineAlias "$site_3_0.lab82" "lblColorEdgeDefault" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.lab82 <Button-1> {
        lambda e: lblColorPicker_OnClick(e)
    }
    label $site_3_0.lab83 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -relief groove 
    vTcl:DefineAlias "$site_3_0.lab83" "lblColorEdgePlayer1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.lab83 <Button-1> {
        lambda e: lblColorPicker_OnClick(e)
    }
    label $site_3_0.lab84 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -relief groove 
    vTcl:DefineAlias "$site_3_0.lab84" "lblColorEdgePlayer2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.lab84 <Button-1> {
        lambda e: lblColorPicker_OnClick(e)
    }
    label $site_3_0.lab85 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -relief groove 
    vTcl:DefineAlias "$site_3_0.lab85" "lblColorEdgeBorder" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.lab85 <Button-1> {
        lambda e: lblColorPicker_OnClick(e)
    }
    place $site_3_0.lab48 \
        -in $site_3_0 -x 20 -y 20 -width 114 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 20 -y 45 -width 114 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 20 -y 73 -width 114 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 20 -y 99 -width 114 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 20 -y 123 -width 114 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 20 -y 148 -width 114 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab80 \
        -in $site_3_0 -x 140 -y 20 -width 40 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 140 -y 46 -width 40 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab82 \
        -in $site_3_0 -x 140 -y 71 -width 40 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 140 -y 98 -width 40 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab84 \
        -in $site_3_0 -x 140 -y 124 -width 40 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab85 \
        -in $site_3_0 -x 140 -y 149 -width 40 -height 20 -anchor nw \
        -bordermode ignore 
    label $top.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Colors 
    vTcl:DefineAlias "$top.lab52" "Label2" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra53 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 155 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 255 
    vTcl:DefineAlias "$top.fra53" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra53
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Node radius} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Horizontal node distance} 
    vTcl:DefineAlias "$site_3_0.lab56" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Vertical node distance} 
    vTcl:DefineAlias "$site_3_0.lab57" "Label3" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi58 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 9} -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable varSpnNodeRadius -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi58" "spnNodeRadius" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi59 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 9} -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable varSpnHorizontalNodeDistance \
        -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi59" "spnHorizontalNodeDistance" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi60 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 9} -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable varSpnVerticalNodeDistance \
        -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi60" "spnVerticalNodeDistance" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi64 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 9} -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable varSpnEdgeWidthDefault \
        -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi64" "spnEdgeWidthDefault" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi65 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 9} -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable varSpnEdgeWidthUsed -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi65" "spnEdgeWidthUsed" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab66 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Edge width default} 
    vTcl:DefineAlias "$site_3_0.lab66" "Label3_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab67 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Edge width used} 
    vTcl:DefineAlias "$site_3_0.lab67" "Label3_9" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 30 -y 20 -width 138 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 30 -y 46 -width 138 -relwidth 0 -height 21 \
        -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 30 -y 70 -width 138 -relwidth 0 -height 21 \
        -anchor nw -bordermode ignore 
    place $site_3_0.spi58 \
        -in $site_3_0 -x 185 -y 21 -width 35 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi59 \
        -in $site_3_0 -x 185 -y 45 -width 35 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi60 \
        -in $site_3_0 -x 185 -y 72 -width 35 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi64 \
        -in $site_3_0 -x 185 -y 98 -width 35 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi65 \
        -in $site_3_0 -x 185 -y 121 -width 35 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 30 -y 97 -width 138 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 30 -y 120 -width 138 -height 21 -anchor nw \
        -bordermode ignore 
    label $top.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Sizes 
    vTcl:DefineAlias "$top.lab54" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but61 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Save 
    vTcl:DefineAlias "$top.but61" "btnSave" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but61 <Button-1> {
        lambda e: btnSave_OnClick(e)
    }
    button $top.but62 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Cancel 
    vTcl:DefineAlias "$top.but62" "btnCancel" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but62 <Button-1> {
        lambda e: btnCancel_OnClick(e)
    }
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 50 -y 226 -width 255 -relwidth 0 -height 185 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 60 -y 210 -width 54 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.fra53 \
        -in $top -x 50 -y 30 -width 255 -relwidth 0 -height 155 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 54 -y 16 -width 54 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.but61 \
        -in $top -x 350 -y 30 -width 65 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but62 \
        -in $top -x 368 -y 90 -width 47 -height 24 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

