#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  Jul 23, 2019 11:52:42 AM CEST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m72" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 514x491+492+213
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1684 1031
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 125 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 105 
    vTcl:DefineAlias "$top.fra43" "frameField" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    radiobutton $site_3_0.rad50 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -indicatoron 0 \
        -justify left -text Football -value football -variable varGroupField \
        -width 60 
    vTcl:DefineAlias "$site_3_0.rad50" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.rad50
    radiobutton $site_3_0.rad51 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -indicatoron 0 \
        -justify left -text Hockey -value hockey -variable varGroupField \
        -width 60 
    vTcl:DefineAlias "$site_3_0.rad51" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.rad51
    radiobutton $site_3_0.rad52 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -indicatoron 0 \
        -justify left -text Rugby -value rugby -variable varGroupField \
        -width 60 
    vTcl:DefineAlias "$site_3_0.rad52" "Radiobutton3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.rad52
    place $site_3_0.rad50 \
        -in $site_3_0 -x 20 -y 20 -width 60 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad51 \
        -in $site_3_0 -x 20 -y 50 -width 60 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad52 \
        -in $site_3_0 -x 20 -y 80 -width 60 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Field 
    vTcl:DefineAlias "$top.lab49" "Label1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra55 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 125 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 105 
    vTcl:DefineAlias "$top.fra55" "frameSize" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra55
    radiobutton $site_3_0.rad50 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -indicatoron 0 \
        -justify left -text Small -value small -variable varGroupSize \
        -width 60 
    vTcl:DefineAlias "$site_3_0.rad50" "Radiobutton1_3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.rad50
    radiobutton $site_3_0.rad51 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -indicatoron 0 \
        -justify left -text Medium -value medium -variable varGroupSize \
        -width 60 
    vTcl:DefineAlias "$site_3_0.rad51" "Radiobutton2_4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.rad51
    radiobutton $site_3_0.rad52 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -indicatoron 0 \
        -justify left -text Big -value big -variable varGroupSize -width 60 
    vTcl:DefineAlias "$site_3_0.rad52" "Radiobutton3_5" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.rad52
    place $site_3_0.rad50 \
        -in $site_3_0 -x 20 -y 20 -width 60 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad51 \
        -in $site_3_0 -x 20 -y 50 -width 60 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad52 \
        -in $site_3_0 -x 20 -y 80 -width 60 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Size 
    vTcl:DefineAlias "$top.lab57" "Label1_6" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra60 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 255 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 185 
    vTcl:DefineAlias "$top.fra60" "framePlayer1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra60
    frame $site_3_0.fra61 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 125 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 105 
    vTcl:DefineAlias "$site_3_0.fra61" "framePlayer1_AIdifficulty" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra61
    radiobutton $site_4_0.rad50 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -indicatoron 0 \
        -justify left -text Easy -value easy -variable varGroupDifficultyAI1 \
        -width 60 
    vTcl:DefineAlias "$site_4_0.rad50" "Radiobutton1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.rad50
    radiobutton $site_4_0.rad51 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -indicatoron 0 \
        -justify left -text Medium -value medium \
        -variable varGroupDifficultyAI1 -width 60 
    vTcl:DefineAlias "$site_4_0.rad51" "Radiobutton2_2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.rad51
    radiobutton $site_4_0.rad52 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -indicatoron 0 \
        -justify left -text Hard -value hard -variable varGroupDifficultyAI1 \
        -width 60 
    vTcl:DefineAlias "$site_4_0.rad52" "Radiobutton3_3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.rad52
    place $site_4_0.rad50 \
        -in $site_4_0 -x 20 -y 20 -width 60 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad51 \
        -in $site_4_0 -x 20 -y 50 -width 60 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad52 \
        -in $site_4_0 -x 20 -y 80 -width 60 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    radiobutton $site_3_0.rad64 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command rdbPlayer1_OnClick \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -indicatoron 0 -justify left -text Human \
        -value human -variable varGroupPlayer1 
    vTcl:DefineAlias "$site_3_0.rad64" "rdbPlayer1_human" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad65 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command rdbPlayer1_OnClick \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -indicatoron 0 -justify left -text AI -value AI \
        -variable varGroupPlayer1 
    vTcl:DefineAlias "$site_3_0.rad65" "rdbPlayer1_AI" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.fra61 \
        -in $site_3_0 -x 40 -y 110 -width 105 -relwidth 0 -height 125 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad64 \
        -in $site_3_0 -x 40 -y 40 -width 60 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad65 \
        -in $site_3_0 -x 40 -y 80 -width 60 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra67 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 255 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 185 
    vTcl:DefineAlias "$top.fra67" "framePlayer2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra67
    frame $site_3_0.fra61 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 125 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 105 
    vTcl:DefineAlias "$site_3_0.fra61" "framePlayer2_AIdifficulty" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra61
    radiobutton $site_4_0.rad50 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -indicatoron 0 \
        -justify left -text Easy -value easy -variable varGroupDifficultyAI2 \
        -width 60 
    vTcl:DefineAlias "$site_4_0.rad50" "Radiobutton1_4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.rad50
    radiobutton $site_4_0.rad51 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -indicatoron 0 \
        -justify left -text Medium -value medium \
        -variable varGroupDifficultyAI2 -width 60 
    vTcl:DefineAlias "$site_4_0.rad51" "Radiobutton2_5" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.rad51
    radiobutton $site_4_0.rad52 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -indicatoron 0 \
        -justify left -text Hard -value hard -variable varGroupDifficultyAI2 \
        -width 60 
    vTcl:DefineAlias "$site_4_0.rad52" "Radiobutton3_6" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.rad52
    place $site_4_0.rad50 \
        -in $site_4_0 -x 20 -y 20 -width 60 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad51 \
        -in $site_4_0 -x 20 -y 50 -width 60 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad52 \
        -in $site_4_0 -x 20 -y 80 -width 60 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    radiobutton $site_3_0.rad64 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command rdbPlayer2_OnClick \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -indicatoron 0 -justify left -text Human \
        -value human -variable varGroupPlayer2 
    vTcl:DefineAlias "$site_3_0.rad64" "rdbPlayer2_human" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad65 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command rdbPlayer2_OnClick \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -indicatoron 0 -justify left -text AI -value AI \
        -variable varGroupPlayer2 
    vTcl:DefineAlias "$site_3_0.rad65" "rdbPlayer2_AI" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.fra61 \
        -in $site_3_0 -x 40 -y 110 -width 105 -relwidth 0 -height 125 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad64 \
        -in $site_3_0 -x 40 -y 40 -width 60 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad65 \
        -in $site_3_0 -x 40 -y 80 -width 60 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {Player 1} 
    vTcl:DefineAlias "$top.lab68" "Label1_11" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {Player 2} 
    vTcl:DefineAlias "$top.lab69" "Label1_12" vTcl:WidgetProc "Toplevel1" 1
    button $top.but70 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 10 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Save 
    vTcl:DefineAlias "$top.but70" "btnSave" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but70 <Button-1> {
        lambda e: btnSave_OnClick(e)
    }
    button $top.but71 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 10} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Cancel 
    vTcl:DefineAlias "$top.but71" "btnCancel" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but71 <Button-1> {
        lambda e: btnCancel_OnClick(e)
    }
    set site_3_0 $top.m72
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 40 -y 30 -width 105 -relwidth 0 -height 125 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 50 -y 20 -width 48 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra55 \
        -in $top -x 180 -y 30 -width 105 -height 125 -anchor nw \
        -bordermode ignore 
    place $top.lab57 \
        -in $top -x 190 -y 20 -width 48 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.fra60 \
        -in $top -x 40 -y 200 -width 185 -relwidth 0 -height 255 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra67 \
        -in $top -x 260 -y 200 -width 185 -height 255 -anchor nw \
        -bordermode ignore 
    place $top.lab68 \
        -in $top -x 50 -y 190 -width 68 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab69 \
        -in $top -x 270 -y 190 -width 68 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.but70 \
        -in $top -x 360 -y 30 -width 117 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but71 \
        -in $top -x 360 -y 90 -width 117 -height 44 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

