#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Jul 23, 2019 11:52:46 AM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import gameSettings_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    gameSettings_support.set_Tk_var()
    top = Toplevel1 (root)
    gameSettings_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    gameSettings_support.set_Tk_var()
    top = Toplevel1 (w)
    gameSettings_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("514x491+492+213")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.frameField = tk.Frame(top)
        self.frameField.place(relx=0.078, rely=0.061, relheight=0.255
                , relwidth=0.204)
        self.frameField.configure(relief='groove')
        self.frameField.configure(borderwidth="2")
        self.frameField.configure(relief="groove")
        self.frameField.configure(background="#d9d9d9")
        self.frameField.configure(highlightbackground="#d9d9d9")
        self.frameField.configure(highlightcolor="black")
        self.frameField.configure(width=105)

        self.Radiobutton1 = tk.Radiobutton(self.frameField)
        self.Radiobutton1.place(relx=0.19, rely=0.16, relheight=0.2
                , relwidth=0.571)
        self.Radiobutton1.configure(activebackground="#ececec")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(indicatoron="0")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text='''Football''')
        self.Radiobutton1.configure(value="football")
        self.Radiobutton1.configure(variable=gameSettings_support.varGroupField)
        self.Radiobutton1.configure(width=60)

        self.Radiobutton2 = tk.Radiobutton(self.frameField)
        self.Radiobutton2.place(relx=0.19, rely=0.4, relheight=0.2
                , relwidth=0.571)
        self.Radiobutton2.configure(activebackground="#ececec")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(indicatoron="0")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(text='''Hockey''')
        self.Radiobutton2.configure(value="hockey")
        self.Radiobutton2.configure(variable=gameSettings_support.varGroupField)
        self.Radiobutton2.configure(width=60)

        self.Radiobutton3 = tk.Radiobutton(self.frameField)
        self.Radiobutton3.place(relx=0.19, rely=0.64, relheight=0.2
                , relwidth=0.571)
        self.Radiobutton3.configure(activebackground="#ececec")
        self.Radiobutton3.configure(activeforeground="#000000")
        self.Radiobutton3.configure(background="#d9d9d9")
        self.Radiobutton3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3.configure(foreground="#000000")
        self.Radiobutton3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3.configure(highlightcolor="black")
        self.Radiobutton3.configure(indicatoron="0")
        self.Radiobutton3.configure(justify='left')
        self.Radiobutton3.configure(text='''Rugby''')
        self.Radiobutton3.configure(value="rugby")
        self.Radiobutton3.configure(variable=gameSettings_support.varGroupField)
        self.Radiobutton3.configure(width=60)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.097, rely=0.041, height=26, width=48)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 11")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Field''')

        self.frameSize = tk.Frame(top)
        self.frameSize.place(relx=0.35, rely=0.061, relheight=0.255
                , relwidth=0.204)
        self.frameSize.configure(relief='groove')
        self.frameSize.configure(borderwidth="2")
        self.frameSize.configure(relief="groove")
        self.frameSize.configure(background="#d9d9d9")
        self.frameSize.configure(highlightbackground="#d9d9d9")
        self.frameSize.configure(highlightcolor="black")
        self.frameSize.configure(width=105)

        self.Radiobutton1_3 = tk.Radiobutton(self.frameSize)
        self.Radiobutton1_3.place(relx=0.19, rely=0.16, relheight=0.2
                , relwidth=0.571)
        self.Radiobutton1_3.configure(activebackground="#ececec")
        self.Radiobutton1_3.configure(activeforeground="#000000")
        self.Radiobutton1_3.configure(background="#d9d9d9")
        self.Radiobutton1_3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1_3.configure(foreground="#000000")
        self.Radiobutton1_3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1_3.configure(highlightcolor="black")
        self.Radiobutton1_3.configure(indicatoron="0")
        self.Radiobutton1_3.configure(justify='left')
        self.Radiobutton1_3.configure(text='''Small''')
        self.Radiobutton1_3.configure(value="small")
        self.Radiobutton1_3.configure(variable=gameSettings_support.varGroupSize)
        self.Radiobutton1_3.configure(width=60)

        self.Radiobutton2_4 = tk.Radiobutton(self.frameSize)
        self.Radiobutton2_4.place(relx=0.19, rely=0.4, relheight=0.2
                , relwidth=0.571)
        self.Radiobutton2_4.configure(activebackground="#ececec")
        self.Radiobutton2_4.configure(activeforeground="#000000")
        self.Radiobutton2_4.configure(background="#d9d9d9")
        self.Radiobutton2_4.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_4.configure(foreground="#000000")
        self.Radiobutton2_4.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_4.configure(highlightcolor="black")
        self.Radiobutton2_4.configure(indicatoron="0")
        self.Radiobutton2_4.configure(justify='left')
        self.Radiobutton2_4.configure(text='''Medium''')
        self.Radiobutton2_4.configure(value="medium")
        self.Radiobutton2_4.configure(variable=gameSettings_support.varGroupSize)
        self.Radiobutton2_4.configure(width=60)

        self.Radiobutton3_5 = tk.Radiobutton(self.frameSize)
        self.Radiobutton3_5.place(relx=0.19, rely=0.64, relheight=0.2
                , relwidth=0.571)
        self.Radiobutton3_5.configure(activebackground="#ececec")
        self.Radiobutton3_5.configure(activeforeground="#000000")
        self.Radiobutton3_5.configure(background="#d9d9d9")
        self.Radiobutton3_5.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3_5.configure(foreground="#000000")
        self.Radiobutton3_5.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3_5.configure(highlightcolor="black")
        self.Radiobutton3_5.configure(indicatoron="0")
        self.Radiobutton3_5.configure(justify='left')
        self.Radiobutton3_5.configure(text='''Big''')
        self.Radiobutton3_5.configure(value="big")
        self.Radiobutton3_5.configure(variable=gameSettings_support.varGroupSize)
        self.Radiobutton3_5.configure(width=60)

        self.Label1_6 = tk.Label(top)
        self.Label1_6.place(relx=0.37, rely=0.041, height=26, width=48)
        self.Label1_6.configure(activebackground="#f9f9f9")
        self.Label1_6.configure(activeforeground="black")
        self.Label1_6.configure(background="#d9d9d9")
        self.Label1_6.configure(disabledforeground="#a3a3a3")
        self.Label1_6.configure(font="-family {Segoe UI} -size 11")
        self.Label1_6.configure(foreground="#000000")
        self.Label1_6.configure(highlightbackground="#d9d9d9")
        self.Label1_6.configure(highlightcolor="black")
        self.Label1_6.configure(text='''Size''')

        self.framePlayer1 = tk.Frame(top)
        self.framePlayer1.place(relx=0.078, rely=0.407, relheight=0.519
                , relwidth=0.36)
        self.framePlayer1.configure(relief='groove')
        self.framePlayer1.configure(borderwidth="2")
        self.framePlayer1.configure(relief="groove")
        self.framePlayer1.configure(background="#d9d9d9")
        self.framePlayer1.configure(highlightbackground="#d9d9d9")
        self.framePlayer1.configure(highlightcolor="black")
        self.framePlayer1.configure(width=185)

        self.framePlayer1_AIdifficulty = tk.Frame(self.framePlayer1)
        self.framePlayer1_AIdifficulty.place(relx=0.216, rely=0.431
                , relheight=0.49, relwidth=0.568)
        self.framePlayer1_AIdifficulty.configure(relief='groove')
        self.framePlayer1_AIdifficulty.configure(borderwidth="2")
        self.framePlayer1_AIdifficulty.configure(relief="groove")
        self.framePlayer1_AIdifficulty.configure(background="#d9d9d9")
        self.framePlayer1_AIdifficulty.configure(highlightbackground="#d9d9d9")
        self.framePlayer1_AIdifficulty.configure(highlightcolor="black")
        self.framePlayer1_AIdifficulty.configure(width=105)

        self.Radiobutton1_1 = tk.Radiobutton(self.framePlayer1_AIdifficulty)
        self.Radiobutton1_1.place(relx=0.19, rely=0.16, relheight=0.2
                , relwidth=0.571)
        self.Radiobutton1_1.configure(activebackground="#ececec")
        self.Radiobutton1_1.configure(activeforeground="#000000")
        self.Radiobutton1_1.configure(background="#d9d9d9")
        self.Radiobutton1_1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1_1.configure(foreground="#000000")
        self.Radiobutton1_1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1_1.configure(highlightcolor="black")
        self.Radiobutton1_1.configure(indicatoron="0")
        self.Radiobutton1_1.configure(justify='left')
        self.Radiobutton1_1.configure(text='''Easy''')
        self.Radiobutton1_1.configure(value="easy")
        self.Radiobutton1_1.configure(variable=gameSettings_support.varGroupDifficultyAI1)
        self.Radiobutton1_1.configure(width=60)

        self.Radiobutton2_2 = tk.Radiobutton(self.framePlayer1_AIdifficulty)
        self.Radiobutton2_2.place(relx=0.19, rely=0.4, relheight=0.2
                , relwidth=0.571)
        self.Radiobutton2_2.configure(activebackground="#ececec")
        self.Radiobutton2_2.configure(activeforeground="#000000")
        self.Radiobutton2_2.configure(background="#d9d9d9")
        self.Radiobutton2_2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_2.configure(foreground="#000000")
        self.Radiobutton2_2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_2.configure(highlightcolor="black")
        self.Radiobutton2_2.configure(indicatoron="0")
        self.Radiobutton2_2.configure(justify='left')
        self.Radiobutton2_2.configure(text='''Medium''')
        self.Radiobutton2_2.configure(value="medium")
        self.Radiobutton2_2.configure(variable=gameSettings_support.varGroupDifficultyAI1)
        self.Radiobutton2_2.configure(width=60)

        self.Radiobutton3_3 = tk.Radiobutton(self.framePlayer1_AIdifficulty)
        self.Radiobutton3_3.place(relx=0.19, rely=0.64, relheight=0.2
                , relwidth=0.571)
        self.Radiobutton3_3.configure(activebackground="#ececec")
        self.Radiobutton3_3.configure(activeforeground="#000000")
        self.Radiobutton3_3.configure(background="#d9d9d9")
        self.Radiobutton3_3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3_3.configure(foreground="#000000")
        self.Radiobutton3_3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3_3.configure(highlightcolor="black")
        self.Radiobutton3_3.configure(indicatoron="0")
        self.Radiobutton3_3.configure(justify='left')
        self.Radiobutton3_3.configure(text='''Hard''')
        self.Radiobutton3_3.configure(value="hard")
        self.Radiobutton3_3.configure(variable=gameSettings_support.varGroupDifficultyAI1)
        self.Radiobutton3_3.configure(width=60)

        self.rdbPlayer1_human = tk.Radiobutton(self.framePlayer1)
        self.rdbPlayer1_human.place(relx=0.216, rely=0.157, relheight=0.137
                , relwidth=0.324)
        self.rdbPlayer1_human.configure(activebackground="#ececec")
        self.rdbPlayer1_human.configure(activeforeground="#000000")
        self.rdbPlayer1_human.configure(background="#d9d9d9")
        self.rdbPlayer1_human.configure(command=gameSettings_support.rdbPlayer1_OnClick)
        self.rdbPlayer1_human.configure(disabledforeground="#a3a3a3")
        self.rdbPlayer1_human.configure(foreground="#000000")
        self.rdbPlayer1_human.configure(highlightbackground="#d9d9d9")
        self.rdbPlayer1_human.configure(highlightcolor="black")
        self.rdbPlayer1_human.configure(indicatoron="0")
        self.rdbPlayer1_human.configure(justify='left')
        self.rdbPlayer1_human.configure(text='''Human''')
        self.rdbPlayer1_human.configure(value="human")
        self.rdbPlayer1_human.configure(variable=gameSettings_support.varGroupPlayer1)

        self.rdbPlayer1_AI = tk.Radiobutton(self.framePlayer1)
        self.rdbPlayer1_AI.place(relx=0.216, rely=0.314, relheight=0.137
                , relwidth=0.324)
        self.rdbPlayer1_AI.configure(activebackground="#ececec")
        self.rdbPlayer1_AI.configure(activeforeground="#000000")
        self.rdbPlayer1_AI.configure(background="#d9d9d9")
        self.rdbPlayer1_AI.configure(command=gameSettings_support.rdbPlayer1_OnClick)
        self.rdbPlayer1_AI.configure(disabledforeground="#a3a3a3")
        self.rdbPlayer1_AI.configure(foreground="#000000")
        self.rdbPlayer1_AI.configure(highlightbackground="#d9d9d9")
        self.rdbPlayer1_AI.configure(highlightcolor="black")
        self.rdbPlayer1_AI.configure(indicatoron="0")
        self.rdbPlayer1_AI.configure(justify='left')
        self.rdbPlayer1_AI.configure(text='''AI''')
        self.rdbPlayer1_AI.configure(value="AI")
        self.rdbPlayer1_AI.configure(variable=gameSettings_support.varGroupPlayer1)

        self.framePlayer2 = tk.Frame(top)
        self.framePlayer2.place(relx=0.506, rely=0.407, relheight=0.519
                , relwidth=0.36)
        self.framePlayer2.configure(relief='groove')
        self.framePlayer2.configure(borderwidth="2")
        self.framePlayer2.configure(relief="groove")
        self.framePlayer2.configure(background="#d9d9d9")
        self.framePlayer2.configure(highlightbackground="#d9d9d9")
        self.framePlayer2.configure(highlightcolor="black")
        self.framePlayer2.configure(width=185)

        self.framePlayer2_AIdifficulty = tk.Frame(self.framePlayer2)
        self.framePlayer2_AIdifficulty.place(relx=0.216, rely=0.431
                , relheight=0.49, relwidth=0.568)
        self.framePlayer2_AIdifficulty.configure(relief='groove')
        self.framePlayer2_AIdifficulty.configure(borderwidth="2")
        self.framePlayer2_AIdifficulty.configure(relief="groove")
        self.framePlayer2_AIdifficulty.configure(background="#d9d9d9")
        self.framePlayer2_AIdifficulty.configure(highlightbackground="#d9d9d9")
        self.framePlayer2_AIdifficulty.configure(highlightcolor="black")
        self.framePlayer2_AIdifficulty.configure(width=105)

        self.Radiobutton1_4 = tk.Radiobutton(self.framePlayer2_AIdifficulty)
        self.Radiobutton1_4.place(relx=0.19, rely=0.16, relheight=0.2
                , relwidth=0.571)
        self.Radiobutton1_4.configure(activebackground="#ececec")
        self.Radiobutton1_4.configure(activeforeground="#000000")
        self.Radiobutton1_4.configure(background="#d9d9d9")
        self.Radiobutton1_4.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1_4.configure(foreground="#000000")
        self.Radiobutton1_4.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1_4.configure(highlightcolor="black")
        self.Radiobutton1_4.configure(indicatoron="0")
        self.Radiobutton1_4.configure(justify='left')
        self.Radiobutton1_4.configure(text='''Easy''')
        self.Radiobutton1_4.configure(value="easy")
        self.Radiobutton1_4.configure(variable=gameSettings_support.varGroupDifficultyAI2)
        self.Radiobutton1_4.configure(width=60)

        self.Radiobutton2_5 = tk.Radiobutton(self.framePlayer2_AIdifficulty)
        self.Radiobutton2_5.place(relx=0.19, rely=0.4, relheight=0.2
                , relwidth=0.571)
        self.Radiobutton2_5.configure(activebackground="#ececec")
        self.Radiobutton2_5.configure(activeforeground="#000000")
        self.Radiobutton2_5.configure(background="#d9d9d9")
        self.Radiobutton2_5.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_5.configure(foreground="#000000")
        self.Radiobutton2_5.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_5.configure(highlightcolor="black")
        self.Radiobutton2_5.configure(indicatoron="0")
        self.Radiobutton2_5.configure(justify='left')
        self.Radiobutton2_5.configure(text='''Medium''')
        self.Radiobutton2_5.configure(value="medium")
        self.Radiobutton2_5.configure(variable=gameSettings_support.varGroupDifficultyAI2)
        self.Radiobutton2_5.configure(width=60)

        self.Radiobutton3_6 = tk.Radiobutton(self.framePlayer2_AIdifficulty)
        self.Radiobutton3_6.place(relx=0.19, rely=0.64, relheight=0.2
                , relwidth=0.571)
        self.Radiobutton3_6.configure(activebackground="#ececec")
        self.Radiobutton3_6.configure(activeforeground="#000000")
        self.Radiobutton3_6.configure(background="#d9d9d9")
        self.Radiobutton3_6.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3_6.configure(foreground="#000000")
        self.Radiobutton3_6.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3_6.configure(highlightcolor="black")
        self.Radiobutton3_6.configure(indicatoron="0")
        self.Radiobutton3_6.configure(justify='left')
        self.Radiobutton3_6.configure(text='''Hard''')
        self.Radiobutton3_6.configure(value="hard")
        self.Radiobutton3_6.configure(variable=gameSettings_support.varGroupDifficultyAI2)
        self.Radiobutton3_6.configure(width=60)

        self.rdbPlayer2_human = tk.Radiobutton(self.framePlayer2)
        self.rdbPlayer2_human.place(relx=0.216, rely=0.157, relheight=0.137
                , relwidth=0.324)
        self.rdbPlayer2_human.configure(activebackground="#ececec")
        self.rdbPlayer2_human.configure(activeforeground="#000000")
        self.rdbPlayer2_human.configure(background="#d9d9d9")
        self.rdbPlayer2_human.configure(command=gameSettings_support.rdbPlayer2_OnClick)
        self.rdbPlayer2_human.configure(disabledforeground="#a3a3a3")
        self.rdbPlayer2_human.configure(foreground="#000000")
        self.rdbPlayer2_human.configure(highlightbackground="#d9d9d9")
        self.rdbPlayer2_human.configure(highlightcolor="black")
        self.rdbPlayer2_human.configure(indicatoron="0")
        self.rdbPlayer2_human.configure(justify='left')
        self.rdbPlayer2_human.configure(text='''Human''')
        self.rdbPlayer2_human.configure(value="human")
        self.rdbPlayer2_human.configure(variable=gameSettings_support.varGroupPlayer2)

        self.rdbPlayer2_AI = tk.Radiobutton(self.framePlayer2)
        self.rdbPlayer2_AI.place(relx=0.216, rely=0.314, relheight=0.137
                , relwidth=0.324)
        self.rdbPlayer2_AI.configure(activebackground="#ececec")
        self.rdbPlayer2_AI.configure(activeforeground="#000000")
        self.rdbPlayer2_AI.configure(background="#d9d9d9")
        self.rdbPlayer2_AI.configure(command=gameSettings_support.rdbPlayer2_OnClick)
        self.rdbPlayer2_AI.configure(disabledforeground="#a3a3a3")
        self.rdbPlayer2_AI.configure(foreground="#000000")
        self.rdbPlayer2_AI.configure(highlightbackground="#d9d9d9")
        self.rdbPlayer2_AI.configure(highlightcolor="black")
        self.rdbPlayer2_AI.configure(indicatoron="0")
        self.rdbPlayer2_AI.configure(justify='left')
        self.rdbPlayer2_AI.configure(text='''AI''')
        self.rdbPlayer2_AI.configure(value="AI")
        self.rdbPlayer2_AI.configure(variable=gameSettings_support.varGroupPlayer2)

        self.Label1_11 = tk.Label(top)
        self.Label1_11.place(relx=0.097, rely=0.387, height=26, width=68)
        self.Label1_11.configure(activebackground="#f9f9f9")
        self.Label1_11.configure(activeforeground="black")
        self.Label1_11.configure(background="#d9d9d9")
        self.Label1_11.configure(disabledforeground="#a3a3a3")
        self.Label1_11.configure(font="-family {Segoe UI} -size 11")
        self.Label1_11.configure(foreground="#000000")
        self.Label1_11.configure(highlightbackground="#d9d9d9")
        self.Label1_11.configure(highlightcolor="black")
        self.Label1_11.configure(text='''Player 1''')

        self.Label1_12 = tk.Label(top)
        self.Label1_12.place(relx=0.525, rely=0.387, height=26, width=68)
        self.Label1_12.configure(activebackground="#f9f9f9")
        self.Label1_12.configure(activeforeground="black")
        self.Label1_12.configure(background="#d9d9d9")
        self.Label1_12.configure(disabledforeground="#a3a3a3")
        self.Label1_12.configure(font="-family {Segoe UI} -size 11")
        self.Label1_12.configure(foreground="#000000")
        self.Label1_12.configure(highlightbackground="#d9d9d9")
        self.Label1_12.configure(highlightcolor="black")
        self.Label1_12.configure(text='''Player 2''')

        self.btnSave = tk.Button(top)
        self.btnSave.place(relx=0.7, rely=0.061, height=44, width=117)
        self.btnSave.configure(activebackground="#ececec")
        self.btnSave.configure(activeforeground="#000000")
        self.btnSave.configure(background="#d9d9d9")
        self.btnSave.configure(disabledforeground="#a3a3a3")
        self.btnSave.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.btnSave.configure(foreground="#000000")
        self.btnSave.configure(highlightbackground="#d9d9d9")
        self.btnSave.configure(highlightcolor="black")
        self.btnSave.configure(pady="0")
        self.btnSave.configure(text='''Save''')
        self.btnSave.bind('<Button-1>',lambda e:gameSettings_support.btnSave_OnClick(e))

        self.btnCancel = tk.Button(top)
        self.btnCancel.place(relx=0.7, rely=0.183, height=44, width=117)
        self.btnCancel.configure(activebackground="#ececec")
        self.btnCancel.configure(activeforeground="#000000")
        self.btnCancel.configure(background="#d9d9d9")
        self.btnCancel.configure(disabledforeground="#a3a3a3")
        self.btnCancel.configure(font="-family {Segoe UI} -size 10")
        self.btnCancel.configure(foreground="#000000")
        self.btnCancel.configure(highlightbackground="#d9d9d9")
        self.btnCancel.configure(highlightcolor="black")
        self.btnCancel.configure(pady="0")
        self.btnCancel.configure(text='''Cancel''')
        self.btnCancel.bind('<Button-1>',lambda e:gameSettings_support.btnCancel_OnClick(e))

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

if __name__ == '__main__':
    vp_start_gui()





